name: Scala and Airflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scala-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests
        run: |
          chmod 0755 sbtx
          ./sbtx test

  airflow-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow pytest
          pip install apache-airflow-providers-google

      - name: Test DAG validation
        run: |
          pytest airflow/tests
